### PR TITLE
MIT License

### PR DESCRIPTION
**Pull request by dmccoystephenson**
Changing the license of the project to MIT.

### CODE REVIEW

**Review by CallumJohnson — APPROVED** [review]
I promote the conversion of the license of Ponder to the MIT license.

**Review by Pasarus — APPROVED** [review]

**Comment by dmccoystephenson** [comment]
@philbgarner

**Comment by philbgarner** [comment]
Agreed.

**Review by philbgarner — APPROVED** [review]

**Comment by dmccoystephenson** [comment]
Thank you gentlemen.

**Pull request merged**
